{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.config.containerRegistry.serverAddress .Values.config.containerRegistry.username .Values.config.containerRegistry.password  .Values.config.containerRegistry.email (printf "%s:%s" .Values.config.containerRegistry.username .Values.config.containerRegistry.password | b64enc) | b64enc }}
{{- end }}
kind: Secret
apiVersion: v1
metadata:
  name: container-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
