kind: Secret
apiVersion: v1
metadata:
  name: container-registry-secret
type: Opaque
data:
  docker-server: {{ .Values.config.containerRegistry.serverAddress | b64enc }}
  docker-username: {{ .Values.config.containerRegistry.username | b64enc }}
  docker-password: {{ .Values.config.containerRegistry.password | b64enc }}
  docker-email: {{ .Values.config.containerRegistry.email | b64enc }}

